### ISSUE TITLE
WatcherTitle get bug

### ISSUE THREAD

**Issue by mirceaiscoding** [mirceaiscoding/netflix-recommendations#45]
In order to replicate:

log in on user "user"

<img width="641" alt="image" src="https://user-images.githubusercontent.com/67867765/173100452-59a8b76d-a693-4d8e-a1cf-c16d3fd2b40f.png">

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Movie4U.EntitiesModels.Models.WatcherGenreModel.Copy(WatcherGenre source) in /Users/binamircea/netflix-recommendations/Movie4U/EntitiesModels/Models/WatcherGenreModel.cs:line 40
   at Movie4U.Utilities.CastUtility.ToModel[TEntity,TModel](TEntity entity) in /Users/binamircea/netflix-recommendations/Movie4U/Utilities/CastUtility.cs:line 13
   at Movie4U.Repositories.GenericRepository`2.GetOneByIdAsync(Object id1, Object id2, Func`2 filler) in /Users/binamircea/netflix-recommendations/Movie4U/Repositories/GenericRepository.cs:line 167
   at Movie4U.Managers.WatcherGenresManager.GetOneByIdAsync(String watcher_name, Int32 genre_id) in /Users/binamircea/netflix-recommendations/Movie4U/Managers/WatcherGenresManager.cs:line 58
   at Movie4U.Managers.WatcherTitlesManager.FillModelsLists(WatcherTitleModel watcherTitleModel) in /Users/binamircea/netflix-recommendations/Movie4U/Managers/WatcherTitlesManager.cs:line 47
   at Movie4U.Managers.WatcherTitlesManager.<GetOneByIdAsync>b__7_0(WatcherTitleModel watcherTitleModel) in /Users/binamircea/netflix-recommendations/Movie4U/Managers/WatcherTitlesManager.cs:line 86
   at Movie4U.Repositories.GenericRepository`2.GetOneByIdAsync(Object id1, Object id2, Func`2 filler) in /Users/binamircea/netflix-recommendations/Movie4U/Repositories/GenericRepository.cs:line 170
   at Movie4U.Managers.WatcherTitlesManager.GetOneByIdAsync(String watcher_name, Int32 netflix_id) in /Users/binamircea/netflix-recommendations/Movie4U/Managers/WatcherTitlesManager.cs:line 88
   at Movie4U.Controllers.WatcherTitlesController.GetWatcherTitleByIdAsync(String Authorization, Int32 netflix_id) in /Users/binamircea/netflix-recommendations/Movie4U/Controllers/WatcherTitlesController.cs:line 51
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

HEADERS
=======
Connection: keep-alive
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en;q=0.9
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQmFzaWNVc2VyIiwibmFtZWlkIjoiYzgyODliMGYtMzhlZS00MGVlLWEyYzAtM2ZmZGQ2YTJhOGIwIiwidW5pcXVlX25hbWUiOiJ1c2VyIiwibmJmIjoxNjU0ODc0NTgwLCJleHAiOjE2NTQ4NzU0ODAsImlhdCI6MTY1NDg3NDU4MH0.Do8AZemKh0GvPF8gCA4SODjf1zL3u_oUmIfgbqMtlSkC_PRo1_rU0otZhqkb_OjujKjMGh6XK4lj6pv9SS7VPg
Cookie: username-localhost-8888="2|1:0|10:1653893620|23:username-localhost-8888|44:ZDEyODMxYWFkZjNjNDRmZDg0YzkzY2MwMzQ1NGM3MGU=|e0dbb0411cf1aebba64acbd503b185b0a1cdd8195a46f623f66e71a42fc0516d"; _xsrf=2|3cfd5ce3|589b8ff8030ba6e3a1fe4b5b2987b5d7|1652364134
Host: localhost:5003
Referer: https://localhost:5003/swagger/index.html
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.3 Safari/605.1.15
```

**Comment by StefanGrigorescu** [comment]
I found that all netflix_id occurences in WatcherTitlesController (also in WatcherTitlesManager) are of type string (old format), while the expected type is int now.

**Comment by StefanGrigorescu** [comment]
My intuition is that we do not have any watcherGenres at the moment a watcherTitle is requested (or any moment).
We should automatically insert them if needed or when a watcher is created (this should be a more straightforward approach).

**Comment by StefanGrigorescu** [comment]
I requested all watcherGenres from first page for my user. This was the response:
`There are no watcher genres stored in the database`

**Comment by StefanGrigorescu** [comment]
Fixed.
The problem was about inexisting watcherGenres.
The solution was creating a watcherGenre everytime a GetOneById method is called and no entry is found and returning the new entry (similar to #46).
