### ISSUE TITLE
Titles and WatcherTitles mapping bug

### ISSUE THREAD

**Issue by StefanGrigorescu** [mirceaiscoding/netflix-recommendations#51]
`AutoMapper.AutoMapperMappingException: Error mapping types.

Mapping types:
EntityQueryable`1 -> List`1
Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[[Movie4U.EntitiesModels.Entities.Title, Movie4U, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]] -> System.Collections.Generic.List`1[[Movie4U.EntitiesModels.Models.TitleModel, Movie4U, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]
 ---> AutoMapper.AutoMapperMappingException: Error mapping types.

Mapping types:
Title -> TitleModel
Movie4U.EntitiesModels.Entities.Title -> Movie4U.EntitiesModels.Models.TitleModel

Type Map configuration:
Title -> TitleModel
Movie4U.EntitiesModels.Entities.Title -> Movie4U.EntitiesModels.Models.TitleModel

Destination Member:
countryModels

 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'outer')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Join[TOuter,TInner,TKey,TResult](IEnumerable`1 outer, IEnumerable`1 inner, Func`2 outerKeySelector, Func`2 innerKeySelector, Func`3 resultSelector)
   at Movie4U.Mappers.ModelsMapper.<>c.<.ctor>b__0_20(Title src, TitleModel dest, List`1 destMember, ResolutionContext context) in F:\Projects\Visual Studio Projects\MSDteam\Movie4U\Mappers\ModelsMapper.cs:line 27
   at lambda_method272(Closure , IQueryable`1 , List`1 , ResolutionContext )
   --- End of inner exception stack trace ---
   at lambda_method272(Closure , IQueryable`1 , List`1 , ResolutionContext )
   --- End of inner exception stack trace ---
   at lambda_method272(Closure , IQueryable`1 , List`1 , ResolutionContext )
   at Movie4U.Repositories.GenericRepository`2.GetAllOrderedAsync(GetAllConfig`1 config, List`1 extraModelFilters, Func`2 filler) in F:\Projects\Visual Studio Projects\MSDteam\Movie4U\Repositories\GenericRepository.cs:line 85
   at Movie4U.Repositories.GenericRepository`2.GetAllFromPageAsync(GetAllConfig`1 config, List`1 extraModelFilters, Func`2 filler) in F:\Projects\Visual Studio Projects\MSDteam\Movie4U\Repositories\GenericRepository.cs:line 128
   at Movie4U.Managers.TitlesManager.GetAllFromPageAsync(GetAllConfig`1 config) in F:\Projects\Visual Studio Projects\MSDteam\Movie4U\Managers\TitlesManager.cs:line 69
   at Movie4U.Controllers.TitlesController.GetAllTitlesFromPageAsync(Int32 orderByFlagsPacked, Int32 whereFlagsPacked, Nullable`1 pageIndex) in F:\Projects\Visual Studio Projects\MSDteam\Movie4U\Controllers\TitlesController.cs:line 25
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

HEADERS
=======
:authority: localhost:5003
:method: GET
:path: /Titles/GetAllFromPage/1
:scheme: https
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,ro-RO;q=0.8,ro;q=0.7
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQWRtaW4iLCJuYW1laWQiOiIxODViZGFhMi05OTk2LTQ5N2YtYTYwOS00ZTNlNzBmNjZlMTciLCJ1bmlxdWVfbmFtZSI6IlN0ZWZhbiIsIm5iZiI6MTY1NTMyNTExMSwiZXhwIjoxNjU1MzI2MDExLCJpYXQiOjE2NTUzMjUxMTF9.APZn1rGQdHl4A4wd3y_HwejOmoy2n5NzafIn_eAQfzA44_p8h1S8hWqAdhvUmgNSbyFHxTcHM9CO9weScBejsQ
Host: localhost:5003
Referer: https://localhost:5003/swagger/index.html
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="102", "Google Chrome";v="102"
whereflagspacked: 0
sec-ch-ua-mobile: ?0
orderbyflagspacked: 0
sec-ch-ua-platform: "Windows"
sec-fetch-site: same-origin
sec-fetch-mode: cors
sec-fetch-dest: empty
`

**Comment by StefanGrigorescu** [comment]
`info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (121ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [t].[netflix_id], [t].[img], [t].[poster], [t].[rating], [t].[runtime], [t].[synopsis], [t].[title], [t].[title_date], [t].[title_type], [t].[top250], [t].[top250tv], [t].[year]
      FROM [Title_Details] AS [t]
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      AutoMapper.AutoMapperMappingException: Error mapping types.

      Mapping types:
      EntityQueryable`1 -> List`1
      Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[[Movie4U.EntitiesModels.Entities.Title, Movie4U, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]] -> System.Collections.Generic.List`1[[Movie4U.EntitiesModels.Models.TitleModel, Movie4U, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]
       ---> AutoMapper.AutoMapperMappingException: Error mapping types.

      Mapping types:
      Title -> TitleModel
      Movie4U.EntitiesModels.Entities.Title -> Movie4U.EntitiesModels.Models.TitleModel

      Type Map configuration:
      Title -> TitleModel
      Movie4U.EntitiesModels.Entities.Title -> Movie4U.EntitiesModels.Models.TitleModel

      Destination Member:
      countryModels

       ---> System.ArgumentNullException: Value cannot be null. (Parameter 'outer')
         at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
         at System.Linq.Enumerable.Join[TOuter,TInner,TKey,TResult](IEnumerable`1 outer, IEnumerable`1 inner, Func`2 outerKeySelector, Func`2 innerKeySelector, Func`3 resultSelector)
         at Movie4U.Mappers.ModelsMapper.<>c.<.ctor>b__0_20(Title src, TitleModel dest, List`1 destMember, ResolutionContext context) in F:\Projects\Visual Studio Projects\MSDteam\Movie4U\Mappers\ModelsMapper.cs:line 27
         at lambda_method366(Closure , IQueryable`1 , List`1 , ResolutionContext )
         --- End of inner exception stack trace ---
         at lambda_method366(Closure , IQueryable`1 , List`1 , ResolutionContext )
         --- End of inner exception stack trace ---
         at lambda_method366(Closure , IQueryable`1 , List`1 , ResolutionContext )
         at Movie4U.Repositories.GenericRepository`2.GetAllOrderedAsync(GetAllConfig`1 config, List`1 extraModelFilters, Func`2 filler) in F:\Projects\Visual Studio Projects\MSDteam\Movie4U\Repositories\GenericRepository.cs:line 89
         at Movie4U.Repositories.GenericRepository`2.GetAllFromPageAsync(GetAllConfig`1 config, List`1 extraModelFilters, Func`2 filler) in F:\Projects\Visual Studio Projects\MSDteam\Movie4U\Repositories\GenericRepository.cs:line 132
         at Movie4U.Managers.TitlesManager.GetAllFromPageAsync(GetAllConfig`1 config) in F:\Projects\Visual Studio Projects\MSDteam\Movie4U\Managers\TitlesManager.cs:line 69
         at Movie4U.Controllers.TitlesController.GetAllTitlesFromPageAsync(Int32 orderByFlagsPacked, Int32 whereFlagsPacked, Nullable`1 pageIndex) in F:\Projects\Visual Studio Projects\MSDteam\Movie4U\Controllers\TitlesController.cs:line 26
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
         at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)`
